version: '3'
services:
  node:
    image: halinapp-nodejs2022q4-node:nodejs2022q4-node
    container_name: halinapp-nodejs2022q4-node
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on: 
      - postgres
    volumes:
     - nodedata:/usr/app/
     - /usr/app/node_modules

  postgres:
    image:  halinapp-nodejs2022q4-postgres:nodejs2022q4-postgres
    container_name: halinapp-nodejs2022q4-postgres
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/lib/postgresql/postgresql.log
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
  pglog:
  nodedata:

networks:
  default:
    driver: bridge